name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
 release:
    description: Whether the app should be released after a successful build
    required: true
    default: false

  package_root:
    description: Directory where NPM/Yarn commands should be run
    required: true
    default: "."

  build_script_name:
    description: Name of the optional NPM build script which is executed before `electron-builder`
    required: false
    default: electron:build
